
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.lang.*;
import static java.lang.System.in;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Utkarsha Gharat
 */
public class loginp extends javax.swing.JFrame {

    /**
     * Creates new form loginp
     */
    public loginp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eid = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        efield = new javax.swing.JTextField();
        pfield = new javax.swing.JPasswordField();
        bupdate = new javax.swing.JButton();
        bcheck = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eid.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        eid.setText("Email-id:");

        pass.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        pass.setText("Password:");

        pfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfieldActionPerformed(evt);
            }
        });

        bupdate.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        bupdate.setText("Update");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });

        bcheck.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        bcheck.setText("Checkinfo");
        bcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcheckActionPerformed(evt);
            }
        });

        bdelete.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        bdelete.setText("Delete");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(eid, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(bupdate)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(bdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(efield, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfield, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eid, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(efield, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfield, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection con1;
    ResultSet check = null;
    PreparedStatement insert;
    Statement st=null;
    JFrame j = new JFrame() ;
    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        // TODO add your handling code here:
        
        /*try {
            st = con1.createStatement();
            Class.forName("com.mysql.jdbc.Driver") ;
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/student_details" ,"root","" );
            System.out.print("connection done");
            insert=con1.prepareStatement("select * from srecord where EMAIL=? and PASSWORD =? ");
            insert.setString(1, efield.getText());
            insert.setString(2, pfield.getText());
            System.out.println(insert.toString()) ;
            String emailid = efield.getText();
            
            boolean check1=insert.execute();
            if(check1) {
                System.out.println("pagal yash");
                new updatep().setVisible(true);
                
            }
            else {
                JOptionPane.showMessageDialog(null, "Incorrect Email-id or Password");
            }
            
            
            
            
           
        } 
        catch(NullPointerException ex) {
            System.out.println(ex);
        }
        catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
        catch (SQLException ex) {
            System.out.println(ex);
        }
        catch (Exception ex) {
            System.out.println(ex);
        } */
        String user = efield.getText();
       String pass = pfield.getText() ;
       
      
       
       String user1 = null , pass1 = null;
       
       Connection con1 = null  ;
       
       PreparedStatement insert ;
       
       ResultSet rs ;
        try {
            Class.forName("com.mysql.jdbc.Driver") ;                          
            //("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_details" ,"root", "" );
           
            insert = con1.prepareStatement("select * from srecord where email = ? and password = ? ");
            insert.setString(1 , user);
            insert.setString(2,pass);
            rs = insert.executeQuery();
          
            
            if(rs.next())
            {   
                
               
                JOptionPane.showMessageDialog( j, "username and password matches") ;
                int a = JOptionPane.showConfirmDialog(j, "Are you sure");
           
            if( a == JOptionPane.YES_OPTION ) {
                
               
                this.setVisible(false);
                
                updatep sec1 = new updatep(user);
                sec1.setVisible(true);
                JOptionPane.showMessageDialog( j, "Login successful.") ;
            }
            
            }
            else
            {
                this.setVisible(true);
                JOptionPane.showMessageDialog( j, "username and password not matches") ;
                efield.setText("");
                pfield.setText(""); 
            }
            
            con1.close();
            
        } 
        catch(NullPointerException ex) {
            System.out.println(ex);
        }
        catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
        catch (SQLException ex) {
            System.out.println(ex);
        }
        catch (Exception ex) {
            System.out.println(ex);
        } 
        finally
        {
            try {
                con1.close();
            } catch (SQLException ex) {
                
            }
            
        }
    }//GEN-LAST:event_bupdateActionPerformed

    private void pfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfieldActionPerformed

    private void bcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcheckActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Sinfo s = new Sinfo();
        s.setVisible(true);
    }//GEN-LAST:event_bcheckActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcheck;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bupdate;
    private javax.swing.JTextField efield;
    private javax.swing.JLabel eid;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField pfield;
    // End of variables declaration//GEN-END:variables
}
