
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Utkarsha Gharat
 */
public class updatep extends javax.swing.JFrame {

    /**
     * Creates new form updatep
     */
    String user = "" ;
    Connection con1;
    PreparedStatement insert;
    ResultSet rs;
    public updatep() {
        super("Student");
        initComponents();
    }
    public updatep(String use) {
        super("Student");
        user = use;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uname = new javax.swing.JLabel();
        uemail = new javax.swing.JLabel();
        ucontact = new javax.swing.JLabel();
        udate = new javax.swing.JLabel();
        ugender = new javax.swing.JLabel();
        uaddress = new javax.swing.JLabel();
        utown = new javax.swing.JLabel();
        upincode = new javax.swing.JLabel();
        ustate = new javax.swing.JLabel();
        ucountry = new javax.swing.JLabel();
        upassword = new javax.swing.JLabel();
        uupdate = new javax.swing.JButton();
        updaten = new javax.swing.JTextField();
        updatee = new javax.swing.JTextField();
        updatecno = new javax.swing.JTextField();
        updatea = new javax.swing.JTextField();
        updatet = new javax.swing.JTextField();
        updatepin = new javax.swing.JTextField();
        updates = new javax.swing.JTextField();
        updatec = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        uenter = new javax.swing.JButton();
        updateg = new javax.swing.JTextField();
        updated = new javax.swing.JTextField();
        updatep = new javax.swing.JTextField();
        jDate11 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uname.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        uname.setText("Name:");

        uemail.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        uemail.setText("Email-id:");

        ucontact.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ucontact.setText("Contact-no:");

        udate.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        udate.setText("Date of Birth:");

        ugender.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ugender.setText("Gender:");

        uaddress.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        uaddress.setText("Address:");

        utown.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        utown.setText("Town/City:");

        upincode.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        upincode.setText("Pincode:");

        ustate.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ustate.setText("State:");

        ucountry.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ucountry.setText("Country:");

        upassword.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        upassword.setText("Password:");

        uupdate.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        uupdate.setText("Update");

        updatea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateaActionPerformed(evt);
            }
        });

        updatepin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepinActionPerformed(evt);
            }
        });

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        uenter.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        uenter.setText("Show");
        uenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uenterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(upassword)
                        .addGap(124, 124, 124)
                        .addComponent(updatecno, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDate11, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uname)
                            .addComponent(uemail)
                            .addComponent(ucontact)
                            .addComponent(udate)
                            .addComponent(utown)
                            .addComponent(ugender))
                        .addGap(84, 84, 84)
                        .addComponent(updatet, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uaddress)
                                .addGap(128, 128, 128))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ucountry)
                                    .addComponent(ustate)
                                    .addComponent(upincode))
                                .addGap(124, 124, 124)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(updatep, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(updaten, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                                        .addComponent(updatee, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(updated, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(updateg, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(139, 139, 139)
                                .addComponent(uenter, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(updatepin, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(updatec, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(updates, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
                            .addComponent(updatea, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(uupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(upassword)
                                    .addComponent(updatep, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(uenter, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uname)
                            .addComponent(updaten, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(uemail))
                    .addComponent(updatee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatecno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ucontact)
                    .addComponent(jDate11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(udate)
                            .addComponent(updated, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142)
                        .addComponent(uaddress))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ugender)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(updateg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(updatea, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(utown)
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updatec, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ucountry)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updatet, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updatepin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upincode))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updates, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ustate))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(uupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatepinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatepinActionPerformed

    private void updateaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateaActionPerformed

    private void uenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uenterActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver") ;
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/student_details" ,"root","" );
            System.out.print("connection done");
            
            /*String stdname = updaten.getText();
            String stdemail = updatee.getText();
            String stdcontact = updatec.getText();
            String stddate = updated.getText();
            String stdgender = updateg.getText();
            String stdaddress = updatea.getText();
            String stdtown = updatet.getText();
            String stdpincode = updatepin.getText();
            String stdstate = updates.getText();
            String stdcountry = updatec.getText();*/
           
            //int stdID = Integer.parseInt(updatep.getText());
            insert=con1.prepareStatement("select * from `srecord` where email='"+user+"'");
            rs = insert.executeQuery();
            System.out.print(rs.next());
            System.out.print(user);
            for(int i= 2 ; i<=10 ; i++ )
            {
                   System.out.print( rs.getString(i)+"  " );
            }
            
                updaten.setText(rs.getString(2));
                updatee.setText(rs.getString(3));
                updatecno.setText(rs.getString(4));
                updated.setText(rs.getString(5));
                String d1 = rs.getString(5) ;
                
                String date = rs.getString(5);
               
            try {
                Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(d1);
                jDate11.setDate(date1);
            } catch (ParseException ex) {
                Logger.getLogger(updatep.class.getName()).log(Level.SEVERE, null, ex);
            }
                        
                updateg.setText(rs.getString(6));
                
                String g11 = rs.getString(6) ;
                if( g11.equals("Male"))
                {
                    
                    gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

                }
                else
                {
                     gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  "Female", "Male", }));
                }
                updatea.setText(rs.getString(7));
                updatet.setText(rs.getString(8));
                updatepin.setText(rs.getString(9));
                updates.setText(rs.getString(10));
                updatec.setText(rs.getString(11));
                
            
            
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(Sinfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Sinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
              
        
        
    }//GEN-LAST:event_uenterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> gender;
    private com.toedter.calendar.JDateChooser jDate11;
    private javax.swing.JLabel uaddress;
    private javax.swing.JLabel ucontact;
    private javax.swing.JLabel ucountry;
    private javax.swing.JLabel udate;
    private javax.swing.JLabel uemail;
    private javax.swing.JButton uenter;
    private javax.swing.JLabel ugender;
    private javax.swing.JLabel uname;
    private javax.swing.JLabel upassword;
    private javax.swing.JTextField updatea;
    private javax.swing.JTextField updatec;
    private javax.swing.JTextField updatecno;
    private javax.swing.JTextField updated;
    private javax.swing.JTextField updatee;
    private javax.swing.JTextField updateg;
    private javax.swing.JTextField updaten;
    private javax.swing.JTextField updatep;
    private javax.swing.JTextField updatepin;
    private javax.swing.JTextField updates;
    private javax.swing.JTextField updatet;
    private javax.swing.JLabel upincode;
    private javax.swing.JLabel ustate;
    private javax.swing.JLabel utown;
    private javax.swing.JButton uupdate;
    // End of variables declaration//GEN-END:variables
}
